### ISSUE TITLE
Search focus function is broken

### ISSUE THREAD

**Issue by eitanaviv** [josdejong/jsoneditor#558]
Search functionality is not working properly - when typing in the search box it shows the results but when pressing the arrows it doesn't scroll you to the search results position as it should be.

**Comment by josdejong** [comment]
Ouch, that's a regression in the latest version published a few days ago. Thanks for reporting! 

Should be fixed now in v5.19.2 (web application v4.6.2)

**Comment by eitanaviv** [comment]
Hi @josdejong, it's still happens in the web version (version 4.6.2).

**Comment by josdejong** [comment]
Can it be related to still having the old version of the application in your browsers cache? (Try Ctrl+F5 to reload the web application)

**Comment by eitanaviv** [comment]
@josdejong, my bad.
CTRL+F5 did the work :)

**Comment by josdejong** [comment]
Pfjiew, you scared me ;)
